### ISSUE TITLE
A line of code missing in lesson 3

### ISSUE THREAD

**Issue by rash97** [dataPipelineAU/learningtensorflow.com#4]
In the sub topic of 'Arrays and working with Images' in 'http://learningtensorflow.com/lesson3/', the code for loading the image (image = mpimg.imread(filename)) is missing and hence it doesn't display the size of the image.

**Comment by robertlayton** [comment]
Thanks for reporting. I've fixed the source -- @Dealsy can you please build, check and deploy?
