### ISSUE TITLE
Lesson 11: Final code runs forever

### ISSUE THREAD

**Issue by banana-peel** [dataPipelineAU/learningtensorflow.com#5]
Hi,
I recently started learning tensorflow and wanted to try out it's distributed learning. However when I tried the code given in lesson 11 it simply kept running forever and didn't stop. I assigned 2 CPUs on the HPC with 2 CPUs per task.

This is code I ran:

```
import numpy as np
import tensorflow as tf

cluster = tf.train.ClusterSpec({"local": ["localhost:2222", "localhost:2223"]})

x = tf.placeholder(tf.float32, 100)


with tf.device("/job:local/task:1"):
    first_batch = tf.slice(x, [0], [50])
    mean1 = tf.reduce_mean(first_batch)

with tf.device("/job:local/task:0"):
    second_batch = tf.slice(x, [50], [-1])
    mean2 = tf.reduce_mean(second_batch)
    mean = (mean1 + mean2) / 2


with tf.Session("grpc://localhost:2222") as sess:
    result = sess.run(mean, feed_dict={x: np.random.random(100)})
    print(result)
```

This is the configuration in my batch file I use to submit jobs on the server

```
#SBATCH --nodes=1

#SBATCH --tasks-per-node=2

#SBATCH --cpus-per-task=2

#SBATCH --time=00:10:00

#SBATCH --mem=10GB
```

Please let me know where I'm going wrong

**Comment by robertlayton** [comment]
Hi, thanks for reaching out. Your code seems fine, obviously there are lots of variables to how its run etc.
Can you run a more straightforward job? One CPU, one operation and that's it. If you can get that working, then we can look into why the multi-CPU job isn't working.
