### ISSUE TITLE
Linear Equations exercise

### ISSUE THREAD

**Issue by mladimir** [dataPipelineAU/learningtensorflow.com#6]
In exercise 2 of the Linear Equations tutorial it is stated that there are 5 points needed to solve the equation for the ellipse. However, in the ellipse equation there are 6 unknown coefficients (A, B, C, D, E, F), so you actually need 6 independent equations (i.e 6 different points) to solve it. Am I missing something or did you forget to add a sixth point?

**Comment by robertlayton** [comment]
Five points should be enough. I double checked, and there is this post: https://math.stackexchange.com/questions/163920/how-to-find-an-ellipse-given-five-points
Can you please verify?
